import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy Page - Heliac Energii Controls Solutions",
  // description: "This is Docs page for Solid Pro",
  // other metadata
};

export default function PrivacyPolicy() {
  return (
    <section className="flex w-full flex-col items-center justify-start pb-16 pt-24 md:pb-20 md:pt-28 lg:pb-24 lg:pt-32">
      <div className="w-full px-4 lg:w-3/4 text-black">
        <h1 className="mb-4 text-3xl font-bold">Privacy Policy</h1>
        <p className="mb-2">Last updated: August 31, 2024</p>
        <p className="mb-4">
          This Privacy Policy describes Our policies and procedures on the
          collection, use, and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="mb-8">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <h2 className="mb-4 text-2xl font-semibold">
          Interpretation and Definitions
        </h2>

        <h3 className="mb-2 text-xl font-semibold">Interpretation</h3>
        <p className="mb-4">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3 className="mb-2 text-xl font-semibold">Definitions</h3>
        <p className="mb-4">For the purposes of this Privacy Policy:</p>
        <ul className="mb-8 list-inside list-disc">
          <li className="mb-2">
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li className="mb-2">
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by or is under common control with a party, where
            "control" means ownership of 50% or more of the shares, equity
            interest or other securities entitled to vote for the election of
            directors or other managing authority.
          </li>
          <li className="mb-2">
            <strong>Company</strong> (referred to as either "the Company", "We",
            "Us" or "Our" in this Agreement) refers to Heliac Energii Controls
            Solutions, Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </li>
          <li className="mb-2">
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device or any other device by a website, containing
            the details of Your browsing history on that website among its many
            uses.
          </li>
          <li className="mb-2">
            <strong>Country</strong> refers to: Kerala, India.
          </li>
          <li className="mb-2">
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </li>
          <li className="mb-2">
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li className="mb-2">
            <strong>Service</strong> refers to the Website.
          </li>
          <li className="mb-2">
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </li>
          <li className="mb-2">
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li className="mb-2">
            <strong>Website</strong> refers to Heliac Energii, accessible from
            www.heliac.com.
          </li>
          <li className="mb-2">
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>
      </div>
    </section>
  );
}
